{{- if and .Values.grafana.enabled .Values.grafana.deployDashboard}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-grafana-dashboard
  labels:
    {{- include "zesty-k8s.labels" . | nindent 4 }}
    grafana_dashboard: "1"
data:
  zesty-k8s-grafana-dashboard.json: |-
{{ .Files.Get "files/grafana-dashboard.json" | indent 4 }}
{{- end }}
---
{{- if and .Values.grafana.enabled .Values.grafana.deployDataSource}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-grafana-datasource
  labels:
    {{- include "zesty-k8s.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://{{ .Values.victoriaMetrics.server.fullnameOverride}}.{{ .Release.Namespace }}:8428
      access: proxy
      isDefault: true
      editable: false
{{- end }}