{{- if or (and .Values.global.cxLogging .Values.global.cxLogging.enabled) (and .Values.cxLogging .Values.cxLogging.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
  name: {{ include "zesty-k8s.self-monitoring.fullname" . }}-clusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zesty-k8s.self-monitoring.fullname" . }}-clusterRole
subjects:
- kind: ServiceAccount
  name: {{ include "zesty-k8s.self-monitoring.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}