apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pilot
  name: {{ include "zesty-k8s.insights.metrics.job.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zesty-k8s.insights.metrics.job.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "zesty-k8s.insights.metrics.job.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
