{{- if .Values.cxLogging.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  schedule: "{{ .Values.selfMonitoring.schedule }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
          {{- toYaml .Values.global.nodeSelector | nindent 10 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
          {{- toYaml .Values.global.tolerations | nindent 10 }}
          {{- end }}
          containers:
            - name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
              image: {{ .Values.image.repository }}:{{ include "zesty-k8s.version" . }}
              command:
                - /bin/metrics
              imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                {{- if ne .Values.encryptedCredentials ""}}
                - name: ENCRYPTED_CREDENTIALS
                  value: {{ .Values.encryptedCredentials | quote }}
                {{- end }}
                - name: CORALOGIX_LOG_URL
                  value: {{ .Values.cxLogging.logUrl }}
                - name: CX_API_KEY
                  value: {{ .Values.cxLogging.apiKey }}
              envFrom:
                - configMapRef:
                    name: "{{ include "zesty-k8s.configmap" . }}"
              resources:
                requests:
                  cpu: {{ .Values.selfMonitoring.resources.requests.cpu }}
                  memory: {{ .Values.selfMonitoring.resources.requests.memory }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "zesty-k8s.self-monitoring.serviceAccountName" . }}
{{- end }}