{{- if or (and .Values.global.cxLogging .Values.global.cxLogging.enabled) (and .Values.cxLogging .Values.cxLogging.enabled) }}
{{- $globalWorkload := .Values.global | default dict -}}
{{- $selfMonitoringWorkload := .Values.selfMonitoring | default dict -}}
{{- $selfMonitoringPodAnnotations := include "zesty-k8s.workload.mergeMaps" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "podAnnotations"
) | fromYaml -}}
{{- $selfMonitoringPodLabels := include "zesty-k8s.workload.mergeMaps" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "podLabels"
) | fromYaml -}}
{{- $selfMonitoringResolvedPodSecurityContext := mergeOverwrite
  (mergeOverwrite
    (deepCopy (dict))
    ((get $selfMonitoringWorkload "podSecurityContext") | default dict)
  )
  ((get $globalWorkload "podSecurityContext") | default dict)
-}}
{{- $selfMonitoringResolvedSecurityContext := mergeOverwrite
  (mergeOverwrite
    (deepCopy (dict))
    ((get $selfMonitoringWorkload "securityContext") | default dict)
  )
  ((get $globalWorkload "securityContext") | default dict)
-}}
{{- include "zesty-k8s.workload.validateContainerSecurityContext" (dict
  "context" $selfMonitoringResolvedSecurityContext
  "path" "selfMonitoring.securityContext"
) -}}
{{- $selfMonitoringLegacyPodSecurityContext := include "zesty-k8s.workload.extractPodSecurityContext" (dict
  "context" $selfMonitoringResolvedSecurityContext
  "path" "selfMonitoring.securityContext"
) | fromYaml -}}
{{- $selfMonitoringContainerSecurityContext := include "zesty-k8s.workload.extractContainerSecurityContext" (dict
  "context" $selfMonitoringResolvedSecurityContext
  "path" "selfMonitoring.securityContext"
) | fromYaml -}}
{{- $selfMonitoringPodSecurityContext := mergeOverwrite (deepCopy ($selfMonitoringLegacyPodSecurityContext | default dict)) ($selfMonitoringResolvedPodSecurityContext | default dict) -}}
{{- $selfMonitoringAffinity := include "zesty-k8s.workload.mergeMaps" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "affinity"
) | fromYaml -}}
{{- $selfMonitoringImagePullSecrets := include "zesty-k8s.workload.resolveImagePullSecrets" (dict
  "root" .
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
) | fromYamlArray -}}
{{- $selfMonitoringTopologySpreadConstraints := include "zesty-k8s.workload.resolveListWithGlobalPrecedence" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "topologySpreadConstraints"
) | fromYamlArray -}}
{{- $selfMonitoringAutomountSAToken := include "zesty-k8s.workload.resolveBool" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "automountServiceAccountToken"
  "fallback" true
) | trim -}}
{{- $selfMonitoringRuntimeClassName := include "zesty-k8s.workload.resolveString" (dict
  "global" $globalWorkload
  "component" $selfMonitoringWorkload
  "key" "runtimeClassName"
  "fallback" ""
) | trim -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  schedule: "{{ .Values.selfMonitoring.schedule }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          {{- with $selfMonitoringPodAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
            app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
            {{- with $selfMonitoringPodLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          automountServiceAccountToken: {{ $selfMonitoringAutomountSAToken }}
          {{- if $selfMonitoringRuntimeClassName }}
          runtimeClassName: {{ $selfMonitoringRuntimeClassName | quote }}
          {{- end }}
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
          {{- toYaml .Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
          {{- toYaml .Values.global.tolerations | nindent 12 }}
          {{- end }}
          {{- with $selfMonitoringAffinity }}
          affinity:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $selfMonitoringTopologySpreadConstraints }}
          topologySpreadConstraints:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $selfMonitoringPodSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
              image: {{ .Values.image.repository }}:{{ include "zesty-k8s.version" . }}
              command:
                - /bin/metrics
              imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                {{- if ne .Values.encryptedCredentials ""}}
                - name: ENCRYPTED_CREDENTIALS
                  value: {{ .Values.encryptedCredentials | quote }}
                {{- end }}
                {{- include "zesty-k8s.monitoring.coralogix.envs" . | nindent 16 }}
              envFrom:
                - configMapRef:
                    name: "{{ include "zesty-k8s.configmap" . }}"
              {{- with .Values.selfMonitoring.resources }}
              resources:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $selfMonitoringContainerSecurityContext }}
              securityContext:
              {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: Never
          {{- if $selfMonitoringImagePullSecrets }}
          imagePullSecrets:
            {{- toYaml $selfMonitoringImagePullSecrets | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "zesty-k8s.self-monitoring.serviceAccountName" . }}
{{- end }}
