{{- if or (and .Values.global.cxLogging .Values.global.cxLogging.enabled) (and .Values.cxLogging .Values.cxLogging.enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
spec:
  schedule: "{{ .Values.selfMonitoring.schedule }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          {{- if .Values.global.nodeSelector }}
          nodeSelector:
          {{- toYaml .Values.global.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.global.tolerations }}
          tolerations:
          {{- toYaml .Values.global.tolerations | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ include "zesty-k8s.self-monitoring.fullname" . }}
              image: {{ .Values.image.repository }}:{{ include "zesty-k8s.version" . }}
              command:
                - /bin/metrics
              imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                {{- if ne .Values.encryptedCredentials ""}}
                - name: ENCRYPTED_CREDENTIALS
                  value: {{ .Values.encryptedCredentials | quote }}
                {{- end }}
                {{- if and .Values.global.cxLogging .Values.global.cxLogging.enabled }}
                - name: CX_CLUSTER_NAME
                  value: {{ .Values.global.cxLogging.clusterName }}
                - name: CX_API_KEY
                  value: {{ .Values.global.cxLogging.apiKey }}
                - name: CORALOGIX_INGRESS_URL
                {{- /*
                For backward compatibility, if the cxLogging.otelEndpoint is provided, use it to generate the ingressUrl.
                To remove in the future.
                */}}
                {{- if .Values.global.cxLogging.otelEndpoint }}
                  value: https://{{ .Values.global.cxLogging.otelEndpoint }}/
                {{- else }}
                  value: {{ .Values.global.cxLogging.ingressUrl }}
                {{- end }}
                {{- else if and .Values.cxLogging .Values.cxLogging.enabled }}
                - name: CX_CLUSTER_NAME
                  value: {{ .Values.cxLogging.clusterName }}
                - name: CX_API_KEY
                  value: {{ .Values.cxLogging.apiKey }}
                - name: CORALOGIX_INGRESS_URL
                {{- /*
                For backward compatibility, if the cxLogging.otelEndpoint is provided, use it to generate the ingressUrl.
                To remove in the future.
                */}}
                {{- if .Values.cxLogging.otelEndpoint }}
                  value: https://{{ .Values.cxLogging.otelEndpoint }}/
                {{- else }}
                  value: {{ .Values.cxLogging.ingressUrl }}
                {{- end }}
                {{- end }}
              envFrom:
                - configMapRef:
                    name: "{{ include "zesty-k8s.configmap" . }}"
              {{- with .Values.selfMonitoring.resources }}
              resources:
              {{- toYaml . | nindent 16 }}
              {{- end }}
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          serviceAccountName: {{ include "zesty-k8s.self-monitoring.serviceAccountName" . }}
{{- end }}
