{{- if or (and .Values.global.cxLogging .Values.global.cxLogging.enabled) (and .Values.cxLogging .Values.cxLogging.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zesty-k8s.self-monitoring.serviceAccountName" . }}
  labels:
    app.kubernetes.io/instance: "{{ include "zesty-k8s.self-monitoring.fullname" . }}"
    app.kubernetes.io/name: "{{ include "zesty-k8s.fullname" . }}"
{{- end }}
