{{- if .Values.cxLogging.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pilot
  name: {{ include "zesty-k8s.insights.monitoring.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
